name: Lint and format the code
run-name: ${{ github.actor }} is formating the code
on: [push]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn lin:fix
      - run: yarn prettier:format
